### ISSUE TITLE
http://boss.bekk.no/display/BOSS/Jack is down

### ISSUE THREAD

**Issue by graingert** [keronsen/jack#8]
@keronsen I can't see anything at this URL

**Comment by keronsen** [comment]
Hi! This library is no longer being actively developed. Sorry about that, I'll remove the URL.

**Comment by graingert** [comment]
@keronsen cool, it looks like this repo is still being used, eg https://github.com/keronsen/jack/pull/6

**Comment by graingert** [comment]
Thanks!
